name: aws sample

on:
  workflow_dispatch:

jobs:
  list-s3-buckets-using-Secret:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: execute AWS CLI
        run: aws s3 ls
      - name: get cloudfront config
        run: aws cloudfront get-distribution-config --id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --query "DistributionConfig" > distribution-config.json

      - name: pwd
        run: pwd
      - name: ls
        run: ls
      - name: cat
        run: cat distribution-config.json

      # 4. ETag の取得
      - name: Extract ETag
        id: extract_etag
        run: |
          etag=$(aws cloudfront get-distribution-config \
            --id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --query "ETag" --output text)
          echo "::set-output name=etag::$etag"

      # 5. Origin Request Policy を CORS-S3Origin に変更
      - name: Update origin request policy in distribution config
        run: |
          sed -i 's/"OriginRequestPolicyId": "[^"]*"/"OriginRequestPolicyId": "088a5e82-23a4-4ebd-8a2a-41c4a4e3bd7a"/' distribution-config.json

      - name: cat
        run: cat distribution-config.json

      - name: origin
        run: aws cloudfront list-origin-request-policies --query 'OriginRequestPolicyList.Items[*].{ID:OriginRequestPolicy.Id,Name:OriginRequestPolicy.OriginRequestPolicyConfig.Name}'

      # 6. CloudFront ディストリビューションを更新
      - name: Update CloudFront distribution
        run: |
          aws cloudfront update-distribution \
            --id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --if-match ${{ steps.extract_etag.outputs.etag }} \
            --distribution-config file://distribution-config.json
