name: aws sample

on:
  workflow_dispatch:

jobs:
  list-s3-buckets-using-Secret:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: execute AWS CLI
        run: aws s3 ls
      - name: get cloudfront config
        run: aws cloudfront get-distribution-config --id E33EVMST0IMI3B > distribution-config.json
      - name: pwd
        run: pwd
      - name: ls
        run: ls
      - name: cat
        run: cat distribution-config.json
